### ISSUE TITLE
Callback never fires on opera 30

### ISSUE THREAD

**Issue by wraithgar** [otalk/getScreenMedia#12]
I'm in Opera 30 and running this function ends in a black hole.  The callback never fires.

**Comment by fippo** [comment]
(not even sure opera supports screen sharing but yeah, this should fire _something_)

**Comment by wraithgar** [comment]
It looks like in opera if `chromeMediaSource` is `screen` nothing ever gets fired.

Setting `chromeMediaSource` to `desktop` does result in an error returning.

**Comment by fippo** [comment]
sounds like an opera bug. i'll see if I can find someone to...

**Comment by fippo** [comment]
oh wait.chromeMediaSource: screen is VERY DANGEROUS unless you know what you're doing. It will get people to write g+ posts saying "YIKES".
Why are you trying that even?

**Comment by legastero** [comment]
@fippo Because in Opera (with no chrome.webstore) this is the code that is run: https://github.com/otalk/getScreenMedia/blob/master/getscreenmedia.js#L89

Gar wasn't using passing any options to getScreenMedia.

**Comment by fippo** [comment]
arrrr.... sounds like we need UA sniffing again.
