### ISSUE TITLE
Extension explanation

### ISSUE THREAD

**Issue by wraithgar** [otalk/getScreenMedia#13]
Nowhere in the docs do I see the fact that the site that is doing the screensharing must provide its own extension for users to install.  This additionally makes the extension examples more confusing because w/o that assumption it's very hard to tell what they're even supposed to be.

**Comment by wraithgar** [comment]
Instead of describing what the extensions do under the hood (which to be honest, as the dev implementing this I don't really care how it works) it would be more helpful if you explained how to deliver the plugin to the user.

**Comment by wraithgar** [comment]
Also maybe a section in the readme that says "By the way turns out screen sharing doesn't work out of the box without extensions"

- installing extensions locally (for dev, for localhost)
- publishing extensions (with domains for your shipped code so your end users can actually screen share

- More information on how to know when you need to tell people they need the extension? (Is this EXTENSION_UNAVAILABLE?)

**Comment by vylan** [comment]
confused too. did you know how to deliver the plugin to user now?

**Comment by fippo** [comment]
@vylan you need to publish the extension to the chrome webstore. See https://developer.chrome.com/webstore/publish

**Comment by vylan** [comment]
thanks, I 've known. It's quite easy.
