### ISSUE TITLE
Cannot read property 'sourceId' of undefined

### ISSUE THREAD

**Issue by Touchpad** [otalk/getScreenMedia#15]
Hiya
I'm trying this one out connected to a server running "simplewebrtc"
but when ever I click the button for sharing screen I'm getting this error message

```Error in event handler for (unknown): TypeError: Cannot read property 'sourceId' of undefined```

what am I missing here, I've never built a chrome extension before

**Comment by fippo** [comment]
looks like this can happen when an error occurs -- see https://developer.chrome.com/extensions/runtime#method-sendMessage

Most likely, no extension is active?

**Comment by Touchpad** [comment]
The problem is I only get this error if I have the extension installed, however I don't get any message in the debugger for the extension 

On 11 August 2015 16:41:05 CEST, Philipp Hancke <notifications@github.com> wrote:
>looks like this can happen when an error occurs -- see
>https://developer.chrome.com/extensions/runtime#method-sendMessage
>
>Most likely, no extension is active?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/otalk/getScreenMedia/issues/15#issuecomment-129911054

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by xdumaine** [comment]
There is an unsafe access of `sourceId` at [L147](https://github.com/otalk/getScreenMedia/blob/master/getscreenmedia.js#L147) - if `event.data` is null, this error would occur.

**Comment by xdumaine** [comment]
Looks like at [L33](https://github.com/otalk/getScreenMedia/blob/master/getscreenmedia.js#L33) we access `data.sourceId` without checking that `data` is truthy/an object - could this be getting an undefined value?

**Comment by fippo** [comment]
@xdumaine yes, in case of an error. @Touchpad easiest solution for now is probably to set a breakpoint and check chrome.runtime.lastError

**Comment by Touchpad** [comment]
I had to abbandon this project for now but I think this might have been caused by code not related to this project, sorry for the incorrect error-reporting
