### ISSUE TITLE
Can not sign firefox extension

### ISSUE THREAD

**Issue by samosale** [otalk/getScreenMedia#25]
I am having problem uploading my extension .zip folder. 
I m getting error: 
```
Sub-package must be signed
Error: Add-ons which contain sub-packages must have all sub-packages signed before uploading.

```

I just zip all 3 files in folder instal.rdf, bootstap.js, screenshare.xpi.

**Comment by tgabi333** [comment]
You should use [jpm](https://www.npmjs.com/package/jpm) to build a proper firefox extension. 

With Firefox 52 you won't need a plugin anymore.

**Comment by samosale** [comment]
Can you suggest me the way how to build it with jpm? I have read all the links but can't figure it out how to combine jpm with bootstraped extension. Jpm init generates package.json file. I can't figure it out how to use bootsraped version of add on with normal way.
