### ISSUE TITLE
Remove webrtc-adapter from package.json

### ISSUE THREAD

**Issue by katranci** [otalk/getScreenMedia#28]
I'm getting the warning below when I install getscreenmedia.

> warning "getscreenmedia@4.0.0" has unmet peer dependency "webrtc-adapter@^3.1.6".

Now that v4 removed inclusion of adapter should it not be also removed from package.json?

**Comment by xdumaine** [comment]
Sorry about the trouble. Peer dependency means you should have webrtc-adapter listed as a dependency alongside getScreenMedia, instead of relying on getScreenMedia to bundle it in. Most of the otalk modules are moving to that pattern. Let me know if you have any more questions or trouble.
