### ISSUE TITLE
Bootstrap extentions not accepted in mozilla repository anymore

### ISSUE THREAD

**Issue by poVoq** [otalk/getScreenMedia#29]
From Firefox 53 onwards, no new legacy add-ons will be accepted on addons.mozilla.org (AMO).

From Firefox 57 onwards, WebExtensions will be the only supported extension type, and Firefox will not load other types.

**Comment by fippo** [comment]
Firefox 52+ no longer needs extensions for screensharing.

**Comment by xdumaine** [comment]
Yep, so we should just remove any reference to the firefox addon and add that to the readme.

**Comment by fippo** [comment]
its already in the readme for the firefox extension. But we might need to go a step further
