### ISSUE TITLE
rename PERMISSION_DENIED error

### ISSUE THREAD

**Issue by fippo** [otalk/getScreenMedia#5]
PERMISSION_DENIED error needs to be renamed to PermissionDeniedError (I think)
Version bump.

**Comment by sualko** [comment]
Today I think it should be NotAllowedError, see https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia.

Should I create a pr?

**Comment by xdumaine** [comment]
@sualko yes please!
